services:
  sdr:
    image: ghcr.io/charlie-foxtrot/rtlsdr-airband:latest
    restart: always
    volumes:
      - ./rtl_airband.conf:/app/rtl_airband.conf
      - ./recordings:/recordings/
    devices:
      - /dev/bus/usb
